version: '3'

services:
  app:
    build:
      context: ./nodejs
    container_name: nodejs
    entrypoint: dockerize --wait tcp://mysql:3306 --timeout 60s docker-entrypoint.sh
    networks:
      - proxy-net
    tty: true
    volumes:
      - ./nodejs:/var/www
    command: bash -c "npm install && node index.js"
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - proxy-net
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    build:
      context: ./mysql
    container_name: mysql
    restart: always
    tty: true
    networks:
      - proxy-net
    volumes:
      - ./mysql/data:/var/lib/mysql

networks:
  proxy-net:
    driver: bridge