version: '3'

services:
  app:
    image: ramoncunha/nodejs-fullcycle
    container_name: nodejs
    networks:
      - proxy-net
    tty: true
    ports:
      - "3000:3000"

  nginx:
    image: ramoncunha/nginx-fullcycle
    container_name: nginx
    networks:
      - proxy-net
    ports:
      - "8080:80"

  db:
    image: ramoncunha/mysql-fullcycle
    container_name: mysql
    restart: always
    tty: true
    networks:
      - proxy-net
    volumes:
      - ./mysql/data:/var/lib/mysql
  
networks:
  proxy-net:
    driver: bridge